
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[profile.default]
src = "src"
out = "out"
libs = ["lib", "dependencies"]
fs_permissions = [
  { access = "read-write", path = "./output"},
  { access = "read", path = "./broadcast" },
  { access = "read", path = "./reports" },
]

[rpc_endpoints]
local = "http://127.0.0.1:8545"
rizenet-testnet = "https://testnet.rizenet.io"

[dependencies]
forge-std = "1.9.6"
"@openzeppelin-contracts" = "5.2.0"
"@openzeppelin-contracts-upgradeable" = "5.2.0"

